global  with sharing class FwAppLiterals extends BaseAppLiterals {
    //list enums here
    //global ENUM PROCESS_NAME {RECORD_TRIGGER, FLOW_TRIGGER, EVENT_RIGGER, SCHEDULE_TRIGGER, BATCH, API_CALLIN, API_CALLOUT, USER_INTERFACE}
    global ENUM ACTION_NAME {CREATE_USER, CREATE_OPPTY, GET_AUTH_TOKEN, POST_RECORD, GET_RECORD}
    global ENUM CLASS_REF {FwServiceLayer, FwCalloutService}

    //list all constants here
}
